### ISSUE TITLE
ppa_helper: ~xenial does not upgrade to ~bionic

### ISSUE THREAD

**Issue by andersk** [pothosware/scripts#1]
Consider using version suffixes like ~ubuntu16.04 and ~ubuntu18.04 rather than ~xenial and ~bionic so that packages will upgrade correctly after a release upgrade.

**Comment by guruofquality** [comment]
thanks, thats a detail I didnt consider now that ubuntu names have wrapped back around

**Comment by guruofquality** [comment]
Added: https://github.com/pothosware/scripts/commit/da413211128bcd8bc57adbd036d57091baff1365
